### ISSUE TITLE
Dump in parallel mode when using SCI  DBSQL_DUPLICATE_KEY_ERROR CX_SY_OPEN_SQL_DB

### ISSUE THREAD

**Issue by Zeatynis** [abaplint/abaplint-sci-client#265]
Hi,
I suppose it is abaplint related because standard SCI variants work ok.
When I use SCI's abaplint variant in AbapGit I get many dumps (attached) about duplicated key when persisting results: CL_CI_INSPECTION=>PERSIST_RESULTS

[DBSQL_DUPLICATE_KEY_ERROR_20220215_092725.zip](https://github.com/abaplint/abaplint/files/8067195/DBSQL_DUPLICATE_KEY_ERROR_20220215_092725.zip)

Have you already encountered something like this? Do you know what could be the issue here and how to fix it? I tried to google it and search in launchpad support but without success.

**Comment by larshp** [comment]
moved issue to [abaplint-sci-client](https://github.com/abaplint/abaplint-sci-client)

**Comment by Zeatynis** [comment]
Nevertheless, the inspection results appear to be correct. Only dumps are irritating. 180+ dumps per inspection.

**Comment by rayatus** [comment]
same here. 

some context:

when in "ABAPGit -> Settings -> Personal > Disable Parallel Processing = false" then ABAPGit triggers that CheckVariant in parallel, so each check is dumping because that "Server is OK abaplint version xxxx" is not pointing to any ObjectType / ObjectName in SCIREST_PS table ('-' instead) 

![image](https://user-images.githubusercontent.com/12736990/212061783-2cb84a9a-32f8-4746-b37e-eb60e17f567a.png)

Maybe just discard that "Server is OK..." message when executed from within ZABAPGit ?

**Comment by rayatus** [comment]
that "ping" is executed by 
```ABAP
zcl_abaplint_check->run_end( )
```
so I just removed those lines regarding ping and no more DUPLICATED_KEY DUMPS
