### ISSUE TITLE
get default configuration from backend

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint-sci-client#9]

**Comment by g-back** [comment]
Now possible, but problem: all responses are automatically parsed and the raw json string is lost. Will either have to make a json writer (which seems excessive) or add another "request" method that works with the raw payload. Thoughts? @sbcgua

**Comment by sbcgua** [comment]
@g-back, not sure I understood the issue well, could you pls give some example ?

**Comment by g-back** [comment]
To get the config from the backend into the SCI config, we need the complete config in "raw" json form, as a string.
Currently, all responses from the backend are automatically parsed with the JSON reader.

option 1) the JSON reader has to have an option to return the raw JSON value as a string (which, unless i'm missing something, would mean to reverse the parsing process or buffer it somehow)
option 2) instead of parsing the JSON of each response by default, allow different types of handling the response (parse the payload json or just retrievee the raw payload json).

**Comment by sbcgua** [comment]
Ah I've got it, you need to serialize it for the screen. Well, the most proper way would be certainly to have serializer too. So happened that I was working on development of such stuff recently, based on the same code - https://github.com/sbcgua/ajson - I needed it for some own projects. There is just one part remaining to enable serializing - maybe a can finish it during this weekend, then we can integrate it actually and have 2 way conversion possibility. What do you think ?

**Comment by sbcgua** [comment]
@g-back have a look to the PR

**Comment by g-back** [comment]
This can be closed I think
