### ISSUE TITLE
Dependencies: Reducing XML size

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint-sci-client#94]
Suggest removing the following,

PROG XML: `<DYNPROS> & <CUA>`

FUGR XML: `<FUNCTIONS>.<DOCUMENTATION> & <DYNPROS> & <CUA>`

**Comment by sbcgua** [comment]
Maybe gzip instead? I don't know if sap http automatically compresses requests. Guess, worth to check it. 

At the same time, if sap can compress requests on http level, it would a lot more efficient than fiddling with compression on json content side...

Just thoughts

**Comment by sbcgua** [comment]
More thoughts. Some kind of class to strip xml would be very useful in abapgit for deployment - i have some ideas, id like to implement in that respect.

**Comment by larshp** [comment]
quick and dirty: https://github.com/abaplint/abaplint-sci-client/pull/95

should do http compression, but currently we are battling some large files and the abaplint XML parser running out of memory

**Comment by larshp** [comment]
and yea, would be nicer if we could inject something to skip the serialization of DYNPROS, like longtexts

**Comment by ed-holland** [comment]
maybe something simple like a flag "minimal_serialization". After that all objects need to be reviewed (and adjusted) for minimal requirements needed for dependency checks.

**Comment by larshp** [comment]
might want to hide this behind some flags, good for later

**Comment by larshp** [comment]
and its quite slow

probably should do the injection trick, but it requires some refactoring in abapGit

**Comment by sbcgua** [comment]
I guess one flag will be not enough. It is not clear what is minimal, and it will mean different for different object types :)

My use case (maybe not directly relevant to this particular issue) is different:
while deploying from one system to another (e.g. non-Hana -> HANA) new stuff appear in XML, so many objects are always yellow. This is due to some specific XML parts. Which might be useful (not to skip them totally) ! But the are missing in original system, so I want to ignore them. Or another case - languages. So my idea was to build an XML postprocessor which would strip both local and remote XMLs before comparing them. And control it with some quick text xpath-like rules which could be entered right into UI e.g. `exclude xml(tabl) /attr1/attr2`

**Comment by sbcgua** [comment]
And then same mech. can be used to reduce xml for abaplint too

**Comment by larshp** [comment]
the scope for this is dependencies, ie. typically SAP standard code. 

For the code "we" write keep as is

**Comment by ed-holland** [comment]
indeed it is quite different from a dependency perspective. 
Probably when we cover PROG, FUGR, CLAS, INTF we already made a big leap forward.
But also for this we need to be careful what we reduce as it might have impact in what is checked.
example Dynpro's: it the dynpro number checked? Are the dynpro fields needed for checks?

We might want to change the check behavior. "If an object that needs to be checked is part of an SAP original", then it is ok Syntax wise and we do not want to check the for coding styles. See #47.

**Comment by larshp** [comment]
note the checked object is serialized by native abapGit, the code in `ZCL_ABAPLINT_DEPS_SERIALIZER` handles serialization of dependencies which does not have errors reported directly

![image](https://user-images.githubusercontent.com/5888506/87850959-7e9cc480-c8f4-11ea-97f5-a23b21910175.png)

**Comment by larshp** [comment]
think this is done, closing
